version: '3.9'

services:
    db:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - django_net

    web:
        build:
            context: ./docker/web
        container_name: django_web
        command: >
            sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./myproject:/app
        working_dir: /app
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - django_net

volumes:
    db_data:

networks:
    django_net:
        driver: bridge
