# Generated by Django 5.2.2 on 2025-07-08 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('trainer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HorseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_weight', models.IntegerField()),
                ('power', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('clear_weather_status', models.IntegerField()),
                ('light_rain_status', models.IntegerField()),
                ('heavy_rain_status', models.IntegerField()),
                ('grass_status', models.IntegerField()),
                ('dirt_status', models.IntegerField()),
                ('sprint_status', models.IntegerField()),
                ('middle_status', models.IntegerField()),
                ('long_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('current_coin', models.IntegerField(default=0)),
                ('login_timestamp', models.DateTimeField(auto_now_add=True)),
                ('login_count', models.IntegerField(default=0)),
                ('number_of_wins', models.IntegerField(default=0)),
                ('number_of_losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='core.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='core.user')),
            ],
        ),
    ]
