# Generated by Django 5.2.2 on 2025-07-09 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horsestats',
            options={'managed': False},
        ),
    ]
