# Generated by Django 5.2.2 on 2025-07-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('current_coin', models.IntegerField(default=0)),
                ('login_timestamp', models.DateTimeField(auto_now_add=True)),
                ('login_count', models.IntegerField(default=0)),
                ('number_of_wins', models.IntegerField(default=0)),
                ('number_of_losses', models.IntegerField(default=0)),
            ],
        ),
    ]
