# Generated by Django 5.2.2 on 2025-06-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserID',
            fields=[
                ('user_id', models.IntegerField(db_column='user_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
