# Generated by Django 5.2.2 on 2025-07-01 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register_name', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttemptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='user_ID', on_delete=django.db.models.deletion.CASCADE, to='register_name.usercredentials')),
            ],
            options={
                'db_table': 'login_attempt_history',
            },
        ),
    ]
