# Generated by Django 5.2.2 on 2025-07-01 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('user_id', models.AutoField(db_column='user_ID', primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('current_coin', models.IntegerField(blank=True, null=True)),
                ('login_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('login_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
